### ISSUE TITLE
tokio-1.43.0 doesn't compile

### ISSUE THREAD

**Issue by realchonk** [thepowersgang/mrustc#355]
This [line](https://github.com/tokio-rs/tokio/blob/2671ffb55b8f2464c0f1c3c7d99ee70118108755/tokio/src/io/stdio_common.rs#L54) (`buf = &buf[..crate::io::blocking::DEFAULT_MAX_BUF_SIZE];`) fails to compile with:
```
--- BUILDING tokio v1.43.0 (75.0% 1r,0w,1b,6c/8t)
> /home/benni/src/work/sdmsh-rs/tools/build/mrustc/bin/mrustc vendor/tokio/src/lib.rs -o output/libtokio-1_43_0.rlib
-C emit-depfile=output/libtokio-1_43_0.rlib.d --cfg debug_assertions -O -L /home/benni/src/work/sdmsh-rs/tools/lib -L output --crate-name tokio --crate-type rlib --crate-tag 1_43_0 --edition 2021 --extern pin_project_lite=output/libpin_project_lite-0_2_16.rlib > output/libtokio-1_43_0.rlib_dbg.txt
 (75.0% 1r,0w,1b,6c/8t): tokio v1.43.0
vendor/tokio/src/io/stdio_common.rs:54:28 error:0:Unexpected token TOK_RWORD_CRATE, expected TOK_SQUARE_CLOSE
Process was terminated with signal 6
FAILING COMMAND: /home/benni/src/work/sdmsh-rs/tools/build/mrustc/bin/mrustc vendor/tokio/src/lib.rs -o output/libtokio-1_43_0.rlib -C emit-depfile=output/libtokio-1_43_0.rlib.d --cfg debug_assertions -O -L /home/benni/src/work/sdmsh-rs/tools/lib -L output --crate-name tokio --crate-type rlib --crate-tag 1_43_0 --edition 2021 --extern pin_project_lite=output/libpin_project_lite-0_2_16.rlib
```

After manually replacing the line, it fails to compile, because `async` is apparently not supported:
```
--- BUILDING tokio v1.43.0 (75.0% 1r,0w,1b,6c/8t)
> /home/benni/src/work/sdmsh-rs/tools/build/mrustc/bin/mrustc vendor/tokio/src/lib.rs -o output/libtokio-1_43_0.rlib
-C emit-depfile=output/libtokio-1_43_0.rlib.d --cfg debug_assertions -O -L /home/benni/src/work/sdmsh-rs/tools/lib -L output --crate-name tokio --crate-type rlib --crate-tag 1_43_0 --edition 2021 --extern pin_project_lite=output/libpin_project_lite-0_2_16.rlib > output/libtokio-1_43_0.rlib_dbg.txt
 (75.0% 1r,0w,1b,6c/8t): tokio v1.43.0
vendor/tokio/src/io/stdio_common.rs:185:25 error:0:Unexpected token TOK_RWORD_ASYNC
Process was terminated with signal 6
FAILING COMMAND: /home/benni/src/work/sdmsh-rs/tools/build/mrustc/bin/mrustc vendor/tokio/src/lib.rs -o output/libtokio-1_43_0.rlib -C emit-depfile=output/libtokio-1_43_0.rlib.d --cfg debug_assertions -O -L /home/benni/src/work/sdmsh-rs/tools/lib -L output --crate-name tokio --crate-type rlib --crate-tag 1_43_0 --edition 2021 --extern pin_project_lite=output/libpin_project_lite-0_2_16.rlib
```

**Comment by thepowersgang** [comment]
What project are you building, and how are you building it?
Note that by default, mrustc works in 1.29 compatibility mode AND it is only expected to work to build rustc/cargo (anything else is a bonus)

**Comment by realchonk** [comment]
I'm trying to rewrite the [https://github.com/EvoLogics/sdmsh](sdmsh) shell for network-based devices in Rust.
And I would like to use mrustc, because right now we can't add full Rust into our SDK.

I'm building mrustc in 1.74.0 compatibility mode using this Makefile:
<details>
<summary>Makefile</summary>

```make
XCC = egcc

TARGET != ./utils/host-triplet
MRUSTC_VER = 0.11.2
RUSTC_VER = 1.74
EXPORTS = CC="${XCC}" MRUSTC_PATH="${PWD}/build/mrustc/bin/mrustc" RUSTC_VERSION=${RUSTC_VER}.0 MRUSTC_TARGET_VER=${RUSTC_VER}

PWD != pwd
T = build/.stamps
U = ${PWD}/utils
GMAKE = env ${EXPORTS} $U/gmake

all: bin/mrustc bin/minicargo lib

clean:
	rm -rf build bin output
	rm -f lib

distclean: clean
	rm -rf src

# DOWNLOAD
download: src/mrustc.tgz src/rustc.tgz

src/mrustc.tgz:
	@mkdir -p src
	#$U/download $@ https://github.com/thepowersgang/mrustc/archive/refs/tags/v${MRUSTC_VER}.tar.gz
	$U/download $@ https://github.com/thepowersgang/mrustc/archive/refs/heads/master.tar.gz

src/rustc.tgz:
	@mkdir -p src
	$U/download $@ https://static.rust-lang.org/dist/rustc-${RUSTC_VER}.0-src.tar.gz

# EXTRACT
extract: $T/mrustc-extract $T/rustc-extract

$T/mrustc-extract: src/mrustc.tgz
	@mkdir -p build $T
	rm -rf build/mrustc
	tar -xzf src/mrustc.tgz -C build/
	mv build/mrustc-* build/mrustc
	touch $@

$T/rustc-extract: src/rustc.tgz
	@mkdir -p build $T
	rm -rf build/rustc
	tar -xzf src/rustc.tgz -C build/
	mv build/rustc-* build/rustc
	touch $@ build/rustc/extracted

# BUILD MRUSTC
$T/mrustc-patch: $T/mrustc-extract
	(cd build/mrustc && patch -Np1) < patches
	touch $@

$T/mrustc-prepare: $T/mrustc-extract
	(cd build/mrustc && ln -sf ../rustc rustc-${RUSTC_VER}.0-src)
	touch $@

$T/mrustc-build-mrustc: $T/mrustc-prepare $T/mrustc-patch $T/rustc-extract
	(cd build/mrustc && ${GMAKE} -j8)
	touch $@

$T/mrustc-build-libs: $T/mrustc-build-mrustc
	(cd build/mrustc && ${GMAKE} -j8 LIBS)
	touch $@

bin/mrustc bin/minicargo: $T/mrustc-build-libs
	@mkdir -p bin
	printf '#!/bin/sh\nexec env ${EXPORTS} ${MRUSTC_PATH} "${PWD}/build/mrustc/bin/$$(basename "$$0")" -L "${PWD}/lib" "$$@"\n' >$@
	chmod +x $@


lib: $T/mrustc-build-libs
	ln -sf build/mrustc/output-${RUSTC_VER}.0 lib

```
</details>

**Comment by thepowersgang** [comment]
Nothing in rustc/cargo needs async blocks, so they are not supported currently

**Comment by realchonk** [comment]
Just out of curiosity, how hard would it be to add async blocks?
I guess they would function similar to closures.

**Comment by thepowersgang** [comment]
They would use similar logic to closures/generators, so it'd mostly be gluing everything together.
However, as rustc/cargo don't need them as of 1.74.0, it's not on the roadmap.

**Comment by thepowersgang** [comment]
Async blocks have been added as part of the 1.90 upgrade. Feel free to give it a try.
