### ISSUE TITLE
Incompatible with bindgen bitfields/incorrect derive clone

### ISSUE THREAD

**Issue by Eroc33** [thepowersgang/mrustc#77]
If code such as the following (used by bindgen) is written:
```
#[repr(C)]
#[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct __BindgenBitfieldUnit<Storage, Align>
where
    Storage: AsRef<[u8]> + AsMut<[u8]>,
{
    storage: Storage,
    align: [Align; 0],
}
```
Mrustc fails with the error `Failed to find an impl of ::"core"::clone::Clone for [Align/*I:1*/; 0]`. This fine in the official compiler, which inserts `Clone` bounds for type parameters where needed, which I assume is what is missing in mrustc.

**Comment by thepowersgang** [comment]
This appears to be a quirk of libcore 1.19.0 - There's only a Clone impl for arrays when the inner type impls Copy. The above works in rustc 1.19 because it has a special case when deriving both Copy and Clone to just have the Clone impl copy the value

**Comment by thepowersgang** [comment]
correction: rustc 1.19.0 (the target version for mrustc) does _not_ compile the above snippet.

```
$ rustc +1.19.0 mrustc-77.rs 
error[E0277]: the trait bound `Align: std::marker::Copy` is not satisfied
 --> mrustc-77.rs:8:5
  |
8 |     align: [Align; 0],
  |     ^^^^^^^^^^^^^^^^^ the trait `std::marker::Copy` is not implemented for `Align`
  |
  = help: consider adding a `where Align: std::marker::Copy` bound
  = note: required because of the requirements on the impl of `std::clone::Clone` for `[Align; 0]`
  = note: required by `std::clone::Clone::clone`

error: aborting due to previous error(s)
```
