### ISSUE TITLE
No member named `_0`

### ISSUE THREAD

**Issue by dtolnay** [thepowersgang/mrustc#57]
`CC=gcc CXX=g++ make -f minicargo.mk` is failing with many errors like the following:

```
output/libcore.hir.o.c:156961:15: error: ‘struct s__ZN4core3str14ParseBoolError’ has no member named ‘_0’
  var0 = & arg0->_0; // Local(0) = Borrow(0, Shared, Field(0, Deref(Argument(0))))
               ^
output/libcore.hir.o.c:156962:4: error: ‘struct s__ZN4core3str14ParseBoolError’ has no member named ‘_0’
  rv._0 = (*var0); // Return = Struct(::"core"::str::ParseBoolError, {Deref(Local(0))})
    ^
```

[Same error in Travis.](https://travis-ci.org/thepowersgang/mrustc/builds/342950983) It looks like this was introduced in c7e76526b54c496708411bf9afcfba2dfa8e4014.

**Comment by thepowersgang** [comment]
Known issue, travis is failing with it.

**Comment by thepowersgang** [comment]
Fixed in 277c6721

**Comment by dtolnay** [comment]
Confirmed fixed. Thanks!
