### ISSUE TITLE
Current master fails to build on macOS 14 with gcc

### ISSUE THREAD

**Issue by barracuda156** [thepowersgang/mrustc#397]
This is a build with gcc 14 on macOS 14.7.1 from 46a04927b3f3825e71aa51002bba45e5783d07da with rustc 1.90.0 (but errors are in mrustc own code).

```
:notice:build --->  Building mrustc
:debug:build Executing org.macports.build (mrustc)
:debug:build Environment: 
:debug:build CC='/opt/local/bin/gcc-mp-14'
:debug:build CC_PRINT_OPTIONS='YES'
:debug:build CC_PRINT_OPTIONS_FILE='/opt/local/var/macports/build/mrustc-6ae41f97/work/.CC_PRINT_OPTIONS'
:debug:build CFG_DEFAULT_LINKER='/opt/local/bin/g++-mp-14'
:debug:build CPATH='/opt/local/include'
:debug:build CXX='/opt/local/bin/g++-mp-14'
:debug:build CXXFLAGS_EXTRA='-Os'
:debug:build DEVELOPER_DIR='/Library/Developer/CommandLineTools'
:debug:build DYLD_LIBRARY_PATH='/opt/local/lib/libgcc'
:debug:build LIBRARY_PATH='/opt/local/lib'
:debug:build LINKFLAGS_EXTRA='-L/opt/local/lib -Wl,-headerpad_max_install_names'
:debug:build MACOSX_DEPLOYMENT_TARGET='14.0'
:debug:build MACPORTS_LEGACY_SUPPORT_DISABLED='1'
:debug:build MRUSTC_TARGET_VER='1.90'
:debug:build RUSTC_TARGET='aarch64-apple-darwin'
:debug:build RUSTC_VERSION='1.90.0'
. . .
:info:build In file included from mir.cpp:9:
:info:build ../../src/mir/mir.hpp:762:11: error: 'Span' does not name a type
:info:build   762 |     const Span& sp;
:info:build       |           ^~~~
:info:build ../../src/mir/mir.hpp:763:18: error: 'Span' does not name a type
:info:build   763 |     Cloner(const Span& sp): sp(sp) {}
:info:build       |                  ^~~~
:info:build ../../src/mir/mir.hpp:776:19: error: 'Monomorphiser' does not name a type
:info:build   776 |     virtual const Monomorphiser& monomorphiser() const;
:info:build       |                   ^~~~~~~~~~~~~
:info:build ../../src/mir/mir.hpp: In constructor 'MIR::Cloner::Cloner(const int&)':
:info:build ../../src/mir/mir.hpp:763:29: error: class 'MIR::Cloner' does not have any field named 'sp'
:info:build   763 |     Cloner(const Span& sp): sp(sp) {}
:info:build       |                             ^~
:info:build In file included from module_tree.hpp:15,
:info:build                  from main.cpp:10:
:info:build ../../src/mir/mir.hpp:762:11: error: 'Span' does not name a type
:info:build   762 |     const Span& sp;
:info:build       |           ^~~~
:info:build ../../src/mir/mir.hpp:763:18: error: 'Span' does not name a type
:info:build   763 |     Cloner(const Span& sp): sp(sp) {}
:info:build       |                  ^~~~
:info:build ../../src/mir/mir.hpp:776:19: error: 'Monomorphiser' does not name a type
:info:build   776 |     virtual const Monomorphiser& monomorphiser() const;
:info:build       |                   ^~~~~~~~~~~~~
:info:build ../../src/mir/mir.hpp: In constructor 'MIR::Cloner::Cloner(const int&)':
:info:build ../../src/mir/mir.hpp:763:29: error: class 'MIR::Cloner' does not have any field named 'sp'
:info:build   763 |     Cloner(const Span& sp): sp(sp) {}
:info:build       |                             ^~
:info:build In file included from module_tree.hpp:15,
:info:build                  from module_tree.cpp:9:
:info:build ../../src/mir/mir.hpp:762:11: error: 'Span' does not name a type
:info:build   762 |     const Span& sp;
:info:build       |           ^~~~
:info:build ../../src/mir/mir.hpp:763:18: error: 'Span' does not name a type
:info:build   763 |     Cloner(const Span& sp): sp(sp) {}
:info:build       |                  ^~~~
:info:build ../../src/mir/mir.hpp:776:19: error: 'Monomorphiser' does not name a type
:info:build   776 |     virtual const Monomorphiser& monomorphiser() const;
:info:build       |                   ^~~~~~~~~~~~~
:info:build ../../src/mir/mir.hpp: In constructor 'MIR::Cloner::Cloner(const int&)':
:info:build ../../src/mir/mir.hpp:763:29: error: class 'MIR::Cloner' does not have any field named 'sp'
:info:build   763 |     Cloner(const Span& sp): sp(sp) {}
:info:build       |                             ^~
:info:build In file included from ../../src/mir/mir.hpp:9:
:info:build mir.cpp: In function 'std::ostream& MIR::operator<<(std::ostream&, const Statement&)':
:info:build ../../src/include/tagged_union.hpp:106:49: warning: enumeration value 'TAG_SaveDropFlag' not handled in switch [-Wswitch]
:info:build   106 | #define TU_MATCH(CLASS, VAR, NAME, ...)   switch( (TU_FIRST VAR).tag()) {/*
:info:build       |                                                 ^
:info:build ../../src/include/tagged_union.hpp:105:37: note: in expansion of macro 'TU_MATCH'
:info:build   105 | #define TU_MATCHA(VARS, NAMES, ...) TU_MATCH( ::std::remove_reference<decltype(TU_FIRST VARS)>::type, VARS, NAMES, __VA_ARGS__ )
:info:build       |                                     ^~~~~~~~
:info:build mir.cpp:395:9: note: in expansion of macro 'TU_MATCHA'
:info:build   395 |         TU_MATCHA( (x), (e),
:info:build       |         ^~~~~~~~~
:info:build ../../src/include/tagged_union.hpp:106:49: warning: enumeration value 'TAG_LoadDropFlag' not handled in switch [-Wswitch]
:info:build   106 | #define TU_MATCH(CLASS, VAR, NAME, ...)   switch( (TU_FIRST VAR).tag()) {/*
:info:build       |                                                 ^
:info:build ../../src/include/tagged_union.hpp:105:37: note: in expansion of macro 'TU_MATCH'
:info:build   105 | #define TU_MATCHA(VARS, NAMES, ...) TU_MATCH( ::std::remove_reference<decltype(TU_FIRST VARS)>::type, VARS, NAMES, __VA_ARGS__ )
:info:build       |                                     ^~~~~~~~
:info:build mir.cpp:395:9: note: in expansion of macro 'TU_MATCHA'
:info:build   395 |         TU_MATCHA( (x), (e),
:info:build       |         ^~~~~~~~~
:info:build mir.cpp: In function 'bool MIR::operator==(const Statement&, const Statement&)':
:info:build ../../src/include/tagged_union.hpp:134:17: warning: enumeration value 'TAG_SaveDropFlag' not handled in switch [-Wswitch]
:info:build   134 |         */switch( tu_match_hdr2_v.tag() ) brace /*
:info:build       |                 ^
:info:build ../../src/include/tagged_union.hpp:131:37: note: in expansion of macro 'TU_MATCH_HDRA_'
:info:build   131 | #define TU_MATCH_HDRA(VARS, brace)  TU_MATCH_HDRA_(::std::remove_reference<decltype(TU_FIRST VARS)>::type, VARS, brace)
:info:build       |                                     ^~~~~~~~~~~~~~
:info:build mir.cpp:683:9: note: in expansion of macro 'TU_MATCH_HDRA'
:info:build   683 |         TU_MATCH_HDRA( (a,b), {)
:info:build       |         ^~~~~~~~~~~~~
:info:build ../../src/include/tagged_union.hpp:134:17: warning: enumeration value 'TAG_LoadDropFlag' not handled in switch [-Wswitch]
:info:build   134 |         */switch( tu_match_hdr2_v.tag() ) brace /*
:info:build       |                 ^
:info:build ../../src/include/tagged_union.hpp:131:37: note: in expansion of macro 'TU_MATCH_HDRA_'
:info:build   131 | #define TU_MATCH_HDRA(VARS, brace)  TU_MATCH_HDRA_(::std::remove_reference<decltype(TU_FIRST VARS)>::type, VARS, brace)
:info:build       |                                     ^~~~~~~~~~~~~~
:info:build mir.cpp:683:9: note: in expansion of macro 'TU_MATCH_HDRA'
:info:build   683 |         TU_MATCH_HDRA( (a,b), {)
:info:build       |         ^~~~~~~~~~~~~
:info:build In file included from module_tree.hpp:15,
:info:build                  from value.cpp:10:
:info:build ../../src/mir/mir.hpp:762:11: error: 'Span' does not name a type
:info:build   762 |     const Span& sp;
:info:build       |           ^~~~
:info:build ../../src/mir/mir.hpp:763:18: error: 'Span' does not name a type
:info:build   763 |     Cloner(const Span& sp): sp(sp) {}
:info:build       |                  ^~~~
:info:build ../../src/mir/mir.hpp:776:19: error: 'Monomorphiser' does not name a type
:info:build   776 |     virtual const Monomorphiser& monomorphiser() const;
:info:build       |                   ^~~~~~~~~~~~~
:info:build ../../src/mir/mir.hpp: In constructor 'MIR::Cloner::Cloner(const int&)':
:info:build ../../src/mir/mir.hpp:763:29: error: class 'MIR::Cloner' does not have any field named 'sp'
:info:build   763 |     Cloner(const Span& sp): sp(sp) {}
:info:build       |                             ^~
:info:build In file included from module_tree.hpp:15,
:info:build                  from hir_sim.cpp:13:
:info:build ../../src/mir/mir.hpp:762:11: error: 'Span' does not name a type
:info:build   762 |     const Span& sp;
:info:build       |           ^~~~
:info:build ../../src/mir/mir.hpp:763:18: error: 'Span' does not name a type
:info:build   763 |     Cloner(const Span& sp): sp(sp) {}
:info:build       |                  ^~~~
:info:build ../../src/mir/mir.hpp:776:19: error: 'Monomorphiser' does not name a type
:info:build   776 |     virtual const Monomorphiser& monomorphiser() const;
:info:build       |                   ^~~~~~~~~~~~~
:info:build ../../src/mir/mir.hpp: In constructor 'MIR::Cloner::Cloner(const int&)':
:info:build ../../src/mir/mir.hpp:763:29: error: class 'MIR::Cloner' does not have any field named 'sp'
:info:build   763 |     Cloner(const Span& sp): sp(sp) {}
:info:build       |                             ^~
:info:build [CXX] miri.cpp
:info:build make: *** [.obj/mir.o] Error 1
:info:build make: *** Waiting for unfinished jobs....
:info:build module_tree.cpp: In member function 'MIR::Function Parser::parse_body(const std::vector<std::__cxx11::basic_string<char> >&)':
:info:build module_tree.cpp:657:58: error: cannot convert '<brace-enclosed initializer list>' to 'MIR::RValue::Data_Borrow'
:info:build   657 |                     src_rval = ::MIR::RValue::make_Borrow({ bt, ::std::move(val) });
:info:build       |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
:info:build In file included from ../../src/mir/mir.hpp:9:
:info:build ../../src/include/tagged_union.hpp:158:39: note:   initializing argument 1 of 'static MIR::RValue::self_t MIR::RValue::make_Borrow(Data_Borrow)'
:info:build   158 |     static self_t make_##__tag(__type v) { return __name( ::std::move(v) ); }\
:info:build       |                                       ^
:info:build ../../src/include/tagged_union.hpp:24:21: note: in definition of macro 'TU_EXP1'
:info:build    24 | #define TU_EXP1(x)  x
:info:build       |                     ^
:info:build ../../src/include/tagged_union.hpp:166:36: note: in expansion of macro 'TU_CONS_I'
:info:build   166 | #define TU_CONS(__name, name, ...) TU_CONS_I(__name, name, TU_DATANAME(name))
:info:build       |                                    ^~~~~~~~~
:info:build ../../src/include/tagged_union.hpp:73:26: note: in expansion of macro 'TU_CONS'
:info:build    73 | #define TU_DISPA(n, a)   n a
:info:build       |                          ^
:info:build ../../src/include/tagged_union.hpp:75:72: note: in expansion of macro 'TU_DISPA'
:info:build    75 | #define TU_DISPA2(n, a, _1, _2)     TU_DISPA(n, (TU_EXP a, TU_EXP _1)) TU_DISPA(n, (TU_EXP a, TU_EXP _2))
:info:build       |                                                                        ^~~~~~~~
:info:build ../../src/include/tagged_union.hpp:77:43: note: in expansion of macro 'TU_DISPA2'
:info:build    77 | #define TU_DISPA4(n, a, a1,a2, b1,b2)     TU_DISPA2(n,a, a1,a2)    TU_DISPA2(n,a, b1,b2)
:info:build       |                                           ^~~~~~~~~
:info:build ../../src/include/tagged_union.hpp:88:75: note: in expansion of macro 'TU_DISPA4'
:info:build    88 | #define TU_DISPA15(n, a, a1,a2,a3,a4, b1,b2,b3,b4, c1,c2,c3,c4, d1,d2,d3) TU_DISPA4(n,a, a1,a2,a3,a4) TU_DISPA4(n,a, b1,b2,b3,b4) TU_DISPA4(n,a, c1,c2,c3,c4) TU_DISPA3(n,a, d1,d2,d3)
:info:build       |                                                                           ^~~~~~~~~
:info:build ../../src/include/tagged_union.hpp:24:21: note: in expansion of macro 'TU_DISPA15'
:info:build    24 | #define TU_EXP1(x)  x
:info:build       |                     ^
:info:build ../../src/include/tagged_union.hpp:247:5: note: in expansion of macro 'TU_CONSS'
:info:build   247 |     TU_CONSS(_name, TU_EXP _variants) \
:info:build       |     ^~~~~~~~
:info:build ../../src/include/tagged_union.hpp:223:5: note: in expansion of macro '_TAGGED_UNION_EX'
:info:build   223 |     _TAGGED_UNION_EX(_name, _inherit, _def, _variants, _extra_move, _extra_assign, _extra)
:info:build       |     ^~~~~~~~~~~~~~~~
:info:build ../../src/mir/mir.hpp:516:1: note: in expansion of macro 'TAGGED_UNION_EX'
:info:build   516 | TAGGED_UNION_EX(RValue, (), Tuple, (
:info:build       | ^~~~~~~~~~~~~~~
:info:build make: *** [.obj/hir_sim.o] Error 1
:info:build make: *** [.obj/main.o] Error 1
:info:build make: *** [.obj/value.o] Error 1
:info:build In file included from module_tree.hpp:15,
:info:build                  from miri.cpp:10:
:info:build ../../src/mir/mir.hpp:762:11: error: 'Span' does not name a type
:info:build   762 |     const Span& sp;
:info:build       |           ^~~~
:info:build ../../src/mir/mir.hpp:763:18: error: 'Span' does not name a type
:info:build   763 |     Cloner(const Span& sp): sp(sp) {}
:info:build       |                  ^~~~
:info:build ../../src/mir/mir.hpp:776:19: error: 'Monomorphiser' does not name a type
:info:build   776 |     virtual const Monomorphiser& monomorphiser() const;
:info:build       |                   ^~~~~~~~~~~~~
:info:build ../../src/mir/mir.hpp: In constructor 'MIR::Cloner::Cloner(const int&)':
:info:build ../../src/mir/mir.hpp:763:29: error: class 'MIR::Cloner' does not have any field named 'sp'
:info:build   763 |     Cloner(const Span& sp): sp(sp) {}
:info:build       |                             ^~
:info:build make: *** [.obj/module_tree.o] Error 1
:info:build miri.cpp: In member function 'bool InterpreterThread::step_one(Value&)':
:info:build miri.cpp:598:15: warning: enumeration value 'TAG_SaveDropFlag' not handled in switch [-Wswitch]
:info:build   598 |         switch(stmt.tag())
:info:build       |               ^
:info:build miri.cpp:598:15: warning: enumeration value 'TAG_LoadDropFlag' not handled in switch [-Wswitch]
:info:build make: *** [.obj/miri.o] Error 1
```

**Comment by thepowersgang** [comment]
Those build errors are from the `standalone_miri` tool, which isn't part of the standard build?
It should be made part of CI, to catch that issue, but mrustc should still work

**Comment by thepowersgang** [comment]
Fixed in 7392eca5bd4958cb184fb47cefbd4c7e4f43547b

**Comment by barracuda156** [comment]
Thank you!
