### ISSUE TITLE
Can't build with GCC 10.2.1

### ISSUE THREAD

**Issue by dkm** [thepowersgang/mrustc#185]
```
cat rust-version > rustc-1.29.0-src//dl-version
+ make -f minicargo.mk LIBS
make -f Makefile all
make[1]: Entering directory '/mnt/barryallen/dkm/git/compiler-explorer/misc-builder/build/mrustc'
[CXX] -o .obj/main.o
In file included from src/hir/type.hpp:13,
                 from src/hir/hir.hpp:23,
                 from src/mir/main_bindings.hpp:10,
                 from src/main.cpp:26:
src/hir/path.hpp: In member function ‘HIR::EncodedLiteralPtr& HIR::EncodedLiteralPtr::operator=(HIR::EncodedLiteralPtr&&)’:
src/hir/path.hpp:33:117: warning: no return statement in function returning non-void [-Wreturn-type]
   33 |     EncodedLiteralPtr& operator=(EncodedLiteralPtr&& x) { this->~EncodedLiteralPtr(); this->p = x.p; x.p = nullptr; }
      |                                                                                                                     ^
      |                                                                                                                     return *this;
In file included from src/parse/token.hpp:11,
                 from src/parse/tokenstream.hpp:15,
                 from src/parse/lex.hpp:13,
                 from src/main.cpp:14:
src/hir/type.hpp: In member function ‘HIR::ArraySize& HIR::ArraySize::operator=(HIR::ArraySize&&)’:
src/include/tagged_union.hpp:150:29: error: the type being destroyed is ‘HIR::ConstGeneric’, but the destructor refers to ‘HIR::ConstGeneric::Data_Unevaluated’ {aka ‘std::shared_ptr<HIR::ExprPtr>’}
  150 | #define TU_DATANAME(name)   Data_##name
      |                             ^~~~~
src/include/tagged_union.hpp:23:21: note: in definition of macro ‘TU_EXP1’
   23 | #define TU_EXP1(x)  x
      |                     ^
src/include/tagged_union.hpp:171:61: note: in expansion of macro ‘TU_DATANAME’
  171 | #define TU_DEST_CASE(tag, ...)  case TAG_##tag: m_data.tag.~TU_DATANAME(tag)(); break;/*
      |                                                             ^~~~~~~~~~~
src/include/tagged_union.hpp:34:31: note: in expansion of macro ‘TU_DEST_CASE’
   34 | #define TU_DISP2(n, _1, _2)   n _1 n _2
      |                               ^
src/include/tagged_union.hpp:23:21: note: in expansion of macro ‘TU_DISP2’
   23 | #define TU_EXP1(x)  x
      |                     ^
src/include/tagged_union.hpp:227:73: note: in expansion of macro ‘TU_DEST_CASES’
  227 | */  _name& operator =(_name&& x) { switch(m_tag) { case TAGDEAD: break; TU_DEST_CASES _variants } m_tag = x.m_tag; TU_EXP _extra_assign switch(m_tag) { case TAGDEAD: break; TU_MOVE_CASES _variants }; return *this; }/*
      |                                                                         ^~~~~~~~~~~~~
src/hir/type.hpp:85:1: note: in expansion of macro ‘TAGGED_UNION_EX’
   85 | TAGGED_UNION_EX(ArraySize, (), Unevaluated, (
      | ^~~~~~~~~~~~~~~
src/hir/type.hpp: In destructor ‘HIR::ArraySize::~ArraySize()’:
src/include/tagged_union.hpp:150:29: error: the type being destroyed is ‘HIR::ConstGeneric’, but the destructor refers to ‘HIR::ConstGeneric::Data_Unevaluated’ {aka ‘std::shared_ptr<HIR::ExprPtr>’}
  150 | #define TU_DATANAME(name)   Data_##name
      |                             ^~~~~
src/include/tagged_union.hpp:23:21: note: in definition of macro ‘TU_EXP1’
   23 | #define TU_EXP1(x)  x
      |                     ^
src/include/tagged_union.hpp:171:61: note: in expansion of macro ‘TU_DATANAME’
  171 | #define TU_DEST_CASE(tag, ...)  case TAG_##tag: m_data.tag.~TU_DATANAME(tag)(); break;/*
      |                                                             ^~~~~~~~~~~
src/include/tagged_union.hpp:34:31: note: in expansion of macro ‘TU_DEST_CASE’
   34 | #define TU_DISP2(n, _1, _2)   n _1 n _2
      |                               ^
src/include/tagged_union.hpp:23:21: note: in expansion of macro ‘TU_DISP2’
   23 | #define TU_EXP1(x)  x
      |                     ^
src/include/tagged_union.hpp:228:53: note: in expansion of macro ‘TU_DEST_CASES’
  228 | */  ~_name() { switch(m_tag) { case TAGDEAD: break; TU_DEST_CASES _variants } m_tag = TAGDEAD; } \
      |                                                     ^~~~~~~~~~~~~
src/hir/type.hpp:85:1: note: in expansion of macro ‘TAGGED_UNION_EX’
   85 | TAGGED_UNION_EX(ArraySize, (), Unevaluated, (
      | ^~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
make[1]: *** [Makefile:306: .obj/main.o] Error 1
```

Is it a known issue? 
Using 5c2626faf4bc157d0ddabf5233eee9db4523fbe7

**Comment by Apteryks** [comment]
I get the same using GCC 10.3.0 on GNU Guix.

**Comment by thepowersgang** [comment]
Interesting, seems like gcc is either spotting a bug, or is getting really confused around that macro magic.
Needs some investigation (might just be a quirk of code working with MSVC but not with gcc).

**Comment by thepowersgang** [comment]
Hmm... Interesting, it's a quirk of method lookup it seems.

The macro expands to `m_data.Unevaluated.~Data_Unevaluated();`, but here it's resolving to `~ConstGeneric::Data_Unevaluated` (`~std::shared_ptr<HIR::ExprPtr>`) instead of `~ArraySize::Data_Unevaluated` (`~ConstGeneric`)

**Comment by thepowersgang** [comment]
Working on a linux re-test and validate currently. More compile and runtime fixes coming.

**Comment by Apteryks** [comment]
> Working on a linux re-test and validate currently. More compile and runtime fixes coming.

Don't mean to be pushy, but a tagged release would be neat after these validations are done :-).

**Comment by dkm** [comment]
> Working on a linux re-test and validate currently. More compile and runtime fixes coming.

Would it be useful to have a github action that simply build and maybe execute a few tests (won't cover windows, only ubuntu) ? I could help with that if you think it's a good idea :)

**Comment by dkm** [comment]
(I can see it builds a bit more now, but still having some errors on `UINT_MAX`, I guess that's what you meant by "more fixes coming")

**Comment by chorman0773** [comment]
I had a few errors myself, mostly with missing includes. I added them locally, I can send a PR later today.

**Comment by thepowersgang** [comment]
Fixed in the above commit, and fully working in 474bec9cfd7862a20e7288cecd7fcf5e18648b9a

I hope to set up actions to build on push this weekend.

**Comment by dkm** [comment]
Great ! Thanks for the quick fix !
