### ISSUE TITLE
Parse macro invocation in repeated $($:item)*

### ISSUE THREAD

**Issue by dtolnay** [thepowersgang/mrustc#59]
This is very similar to #55, still trying to get the libc crate to compile. The following is minimized from their use of `cfg_if!` and compiles with rustc 1.19.0 but not mrustc.

```rust
macro_rules! outer {
    ({ $($x:item)* }) => {}
}

outer! {
    {inner!{}}
}
```

```
libc/src/lib.rs:5: error:0:Expected token in match arm
```
